name: hello-world
on: 
  push:
    branches: 
      - feature/mostapi-networktrac-0-1-0
    tags:
      - v0.1.0
      - v0.2.0
      - v0.3.0
      - v0.4.0
      - v0.5.0
      - v0.6.0

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: uptime
        run: uptime
  my-job-api:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: uptime
        run: uptime
  tag-v-0-1-1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Tag Pushed_v0.1.0"
      - name: grep os level processs
        run: ps -ef |grep java
  job-username:
    runs-on: ubuntu-latest
    steps:
      - name: Step01-OS - Username
        run:  uname -a
      - name: Step02 - OS - id
        run:  id 
      - name: echo "we are runing this step to fecth OS - Leve process list"
        run: ps -ef |grep root
      - name: get total count of OS Level running Process'e 
        run: ps -ef |grep java |wc -l 
  job-filesystem:
    runs-on: ubuntu-latest
    steps:
      - name: list root filesystem
        run: ls -lrt 
      - name: list directory on root filesystem
        run: ls -lrtd /
      - name: find modified files from last 2 mints
        run: find /tmp -mtime -2 

